#!/usr/bin/env bash

if [ -s /etc/DOCUMENT_ROOT ]; then
    DOCUMENT_ROOT=`cat /etc/DOCUMENT_ROOT`
else
    echo ${DOCUMENT_ROOT} > /etc/DOCUMENT_ROOT
fi

if [ ! -d  "/var/www/$DOCUMENT_ROOT" ]; then
  echo "Creating folder /var/www/$DOCUMENT_ROOT"
  mkdir -p "/var/www/$DOCUMENT_ROOT"
else
  echo "/var/www/$DOCUMENT_ROOT already exists."
fi

echo "Setting document root to /var/www/$DOCUMENT_ROOT"
cp /etc/nginx/sites-available/site.conf /tmp
sed -i -e 's,root /var/www/html,root /var/www/'"$DOCUMENT_ROOT"',g' /tmp/site.conf
cat /tmp/site.conf > /etc/nginx/sites-available/site.conf
